name: AnanseScanpy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.8
  - scanpy >=1.9.1
#  - numba >=0.56.3  # numpy
  - numpy <1.24
  - anndata >=0.8.0  # for convenience
  - scipy >=1.9.1
  - pandas >=1.4.4
  - jupyterlab >=3.4.6  # for convenience
  - packaging >=21.3
  - jinja2 >=3.0

# for development
  - black
  - pytest
  - pip >=22.2.2
