name: AnanseScanpy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.8
  - scanpy >=1.9.1
  - numba >=0.56.3  # numpy
  - numpy >=1.23.3, <1.24
  - anndata >=0.8.0  # for convenience
  - scipy >=1.9.1
  - pandas >=1.4.4
  - packaging >=21.3 # statsmodels

# for development
  - black
  - pytest
  - pip >=22.3.1
